sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t armand1m/mono-oracle .

script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$HUB_USERNAME" -p="$HUB_PASSWORD";
    docker push armand1m/mono-oracle;
    fi